# Generated by Django 2.2.3 on 2019-07-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('account_state', models.CharField(choices=[('co', 'confirmed'), ('su', 'set-up'), ('ac', 'active'), ('ca', 'cancelled')], default='co', max_length=2)),
                ('services', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service')),
            ],
        ),
    ]
